export const TV_NEW_CONTENT = {
  slide1: {
    bg: '/tv/slide1.jpg',
    overlay: 'bg-[#123932]/55',
    title: 'Ganzheitliche Betreuung\nfür ein gesundes Leben',
    subtitle: 'Bei uns bist Du mehr als nur ein weiterer Patient',
  },
  slide2: {
    bg: '/tv-new/assets/photo-botox.jpg',
    overlay: 'bg-[#143932]/55',
    kicker: 'Botox',
    title: 'Mehr Lebensqualität',
    subtitle: 'Medizinisch präzise. Natürlich im Ergebnis.',
    sections: {
      medical: ['Hyperhidrose', 'Migräne', 'Bruxismus'],
      aesthetics: ['Faltenbehandlung', 'Gesichtsstraffung'],
    },
    infoUrl: 'praxisjona.de/botox-preise',
    qr: '/tv-new/qr/qr-main.png',
    qrLabel: 'Mehr erfahren',
  },
  slide3: {
    bg: '/tv/slide3.jpg',
    overlay: 'bg-[#123932]/42',
    title: 'Folge mir auf Instagram',
    handle: '@doc.jonida',
    qr: '/tv-new/qr/qr-instagram.png',
    qrLabel: 'Instagram',
  },
  slide4: {
    bg: '/tv-new/assets/photo-ultrasound.jpg',
    overlay: 'bg-[#123932]/60',
    kicker: 'Leistungen',
    title: 'Private Medizin\nmit Struktur',
    subtitle: 'Schnell, persönlich, diskret.',
    items: [
      'Check-up',
      'Ernährungsberatung',
      'Infusionstherapie',
      'Botox',
      'Ultraschalluntersuchung',
      'Reiseimpfungen',
      'Nährstofftherapie',
    ],
    infoUrl: 'praxisjona.de/leistungen',
    qr: '/tv-new/qr/qr-main.png',
    qrLabel: 'Mehr erfahren',
  },
  slide5: {
    bg: '/tv/slide5.jpg',
    overlay: 'bg-[#123932]/46',
    title: 'Bewerten Sie uns\nauf Google',
    qr: '/tv-new/qr/qr-google.png',
    qrLabel: 'Google Bewertung',
  },
  slide6: {
    bg: '/tv-new/assets/photo-walk.jpg',
    overlay: 'bg-[#133831]/58',
    kicker: 'Abnehmspritze',
    title: 'Ärztlich begleitet\nabnehmen',
    subtitle: 'Langfristig, sicher, individuell abgestimmt.',
    bullets: [
      'Reduziert Hungergefühl',
      'Fördert schnelleres Sättigungsgefühl',
      'Teil eines langfristigen Behandlungsplans',
    ],
    infoUrl: 'praxisjona.de/leistungen/abnehmspritze',
    qr: '/tv-new/qr/qr-main.png',
    qrLabel: 'Mehr erfahren',
  },
  slide7: {
    bg: '/tv/slide7.jpg',
    overlay: 'bg-[#123932]/54',
    kicker: 'App',
    title: 'Velto\nGLP-1 Tracker',
    subtitle: 'Fortschritt, Nebenwirkungen und Motivation an einem Ort.',
    note: 'Entwickelt von Praxis Jona und MoneyCoach UG.',
    qr: '/tv-new/qr/qr-app.png',
    qrLabel: 'App laden',
  },
  slide8: {
    bg: '/tv-new/assets/photo-blood.jpg',
    overlay: 'bg-[#123932]/60',
    kicker: 'Diagnostik',
    title: 'Mikronährstoffanalyse',
    subtitle: 'Klarheit statt Rätselraten.',
    left: ['Anhaltende Müdigkeit', 'Konzentrationsprobleme', 'Infektanfälligkeit'],
    right: ['Klare Ergebnisse', 'Individuelle Empfehlung', 'Gezielte Supplementierung'],
    infoUrl: 'praxisjona.de/leistungen/mikronahrstoffanalyse',
    qr: '/tv-new/qr/qr-main.png',
    qrLabel: 'Mehr erfahren',
  },
  slide9: {
    bg: '/tv-new/assets/photo-infusion.jpg',
    overlay: 'bg-[#123932]/60',
    kicker: 'Therapie',
    title: 'Infusionstherapie',
    subtitle: 'Nährstoffe direkt verfügbar.',
    bullets: [
      'Erschöpfung und Leistungsabfall',
      'Individuelle Auswahl der Infusion',
      'Medizinisch überwachte Anwendung',
    ],
    infoUrl: 'praxisjona.de/leistungen/mikronahrstoffanalyse',
    qr: '/tv-new/qr/qr-main.png',
    qrLabel: 'Mehr erfahren',
  },
  slide10: {
    bg: '/tv/slide10.jpg',
    overlay: 'bg-[#10352e]/60',
    kicker: 'Prävention',
    title: 'GESUNDHEIT\nIST KEIN\nZUFALL.',
    subtitle: 'Interdisziplinär. Wissenschaftlich. Persönlich.',
    qr: '/tv-new/qr/qr-main.png',
    qrLabel: 'Mehr erfahren',
  },
  slide11: {
    bg: '/tv/slide11.jpg',
    overlay: 'bg-[#10352e]/60',
    kicker: 'Unser Ansatz',
    title: 'WIR DENKEN\nPRÄVENTION\nNEU.',
    subtitle: 'Klar, strukturiert und auf Dich zugeschnitten.',
    cards: [
      ['DIAGNOSTIK', 'standardisiert und vergleichbar'],
      ['AUSWERTUNG', 'interdisziplinär und verständlich'],
      ['UMSETZUNG', 'konkret und alltagstauglich'],
    ],
    qr: '/tv-new/qr/qr-main.png',
    qrLabel: 'Mehr erfahren',
  },
  slide12: {
    bg: '/tv/slide12.jpg',
    overlay: 'bg-[#10352e]/62',
    kicker: 'Ablauf',
    title: 'IN 3\nSCHRITTEN.',
    subtitle: 'Abgestimmt, interdisziplinär und separat buchbar.',
    steps: [
      ['1', 'ERSTGESPRÄCH', 'Ziele und Vorgeschichte klären'],
      ['2', 'DIAGNOSTIK', 'Messwerte, Tests, Screening'],
      ['3', 'ERGEBNIS & PLAN', 'Konkrete Schritte, begleitet von uns'],
    ],
    qr: '/tv-new/qr/qr-main.png',
    qrLabel: 'Mehr erfahren',
  },
  slide13: {
    bg: '/tv/slide13.jpg',
    overlay: 'bg-[#10352e]/58',
    kicker: 'Team',
    title: 'DEIN EXPERTENTEAM\nFÜR GESUNDHEIT.',
    subtitle: 'Gemeinsam für Deine langfristige Gesundheit.',
    team: [
      { image: '/images/team/jonida-image.jpeg', name: 'Dr. med. Jonida Gjolli', role: 'Ärztliche Leitung & Diagnostik' },
      { image: '/images/team/kathrin-wall.jpg', name: 'Kathrin Schmidt', role: 'Psychologische Betreuung & mentale Gesundheit' },
      { image: '/images/team/junia-gym.jpeg', name: 'Junia Keutel', role: 'Bewegungsdiagnostik & funktionales Training' },
    ],
  },
} as const;
