import { Constants } from "app/Constants";
import type { CategoryContent, LandingContent } from "app/components/pageContent";

export const internalMedicineCategoryContent = {
  generalDe: {
    locale: "de",
    title: "Innere Medizin in Berlin-Mitte",
    eyebrow: "INNERE MEDIZIN & HAUSÄRZTLICHE LEISTUNGEN",
    description: "Praxis Jona am Rosenthaler Platz, hausärztliche Versorgung, Schilddrüsendiagnostik, Vorsorgeuntersuchungen, Akuttermine und moderne internistische Diagnostik in Berlin-Mitte.",
    cta: "Termin buchen",
    ctaHref: Constants.appointmentUrl,
    secondaryCta: "Kontakt aufnehmen",
    secondaryHref: "/kontakt",
    sections: [
      {
        title: "Moderne hausärztliche Medizin, Vorsorge und Schilddrüsendiagnostik am Rosenthaler Platz",
        intro: "Von Akutmedizin und Check-ups bis zu Ultraschall, Langzeitdiagnostik und langfristiger Betreuung chronischer Erkrankungen, individuell, modern und ganzheitlich.",
        services: [
          { title: "Schilddrüse", href: "/schwerpunkte/schilddruese", description: "Schilddrüsendiagnostik mit Labor, Ultraschall und Einordnung häufiger Funktionsstörungen." },
          { title: "Akutsprechstunde", href: "/hausaerztliche-leistungen/akutsprechstunde", description: "Einschätzung akuter Beschwerden mit klarer Empfehlung zum weiteren Vorgehen." },
          { title: "Langzeit-Blutdruckmessung", href: "/hausaerztliche-leistungen/langzeit-blutdruckmessung", description: "24-Stunden-Blutdruckmessung zur realistischen Beurteilung Ihrer Werte im Alltag." },
          { title: "Ultraschalluntersuchung", href: "/hausaerztliche-leistungen/ultraschalluntersuchung", description: "Schonende Sonographie von Bauchorganen, Schilddrüse und ausgewählten Gefäßen." },
          { title: "Gesundheitsuntersuchung", href: "/hausaerztliche-leistungen/gesundheitsuntersuchung-check-up", description: "Gesetzlicher Check-up zur Früherkennung häufiger internistischer Erkrankungen." },
          { title: "EKG", href: "/hausaerztliche-leistungen/ekg", description: "Ruhe-EKG und Belastungs-EKG zur Beurteilung von Herzrhythmus und Belastbarkeit." },
          { title: "Prä- und postoperative Versorgung", href: "/hausaerztliche-leistungen/praeoperative-untersuchung", description: "Hausärztliche Abklärung vor Operationen und Begleitung im weiteren Verlauf." },
          { title: "Impfungen", href: "/hausaerztliche-leistungen/impfungen", description: "Impfstatus-Check, Auffrischungen und individuelle Impfberatung nach STIKO." },
        ],
      },
    ],
    faq: [
      { question: "Kann ich mit akuten Beschwerden kommen?", answer: "Bitte kontaktieren Sie die Praxis vorab, besonders bei Fieber oder ansteckenden Symptomen. So können wir den passenden Ablauf planen." },
      { question: "Welche Leistungen sind gesetzlich?", answer: "Die gesetzliche Versorgung umfasst unter anderem hausärztliche Betreuung, Impfberatung und Check-ups nach den Vorgaben der Krankenkassen." },
      { question: "Wo befindet sich die Praxis?", answer: "Die Praxis Jona liegt in der Torstraße 125 in Berlin-Mitte, gut erreichbar am Rosenthaler Platz." },
    ],
  },
  generalEn: {
    locale: "en",
    title: "Internal Medicine in Berlin-Mitte",
    eyebrow: "General & Internal Medicine",
    description: "Praxis Jona near Rosenthaler Platz: primary care, thyroid diagnostics, preventive check-ups, acute appointments and modern internal medicine diagnostics in Berlin-Mitte.",
    cta: "Book appointment",
    ctaHref: Constants.appointmentUrl,
    secondaryCta: "Contact",
    secondaryHref: "/en/contact",
    sections: [
      {
        title: "Modern primary care, preventive medicine and thyroid diagnostics near Rosenthaler Platz",
        intro: "From acute care and check-ups to ultrasound, long-term diagnostics and ongoing support for chronic conditions, individually, modernly and holistically.",
        services: [
          { title: "Thyroid diagnostics", href: "/en/focus-areas/thyroid-gland", description: "Thyroid assessment with lab testing, ultrasound and interpretation of common dysfunctions." },
          { title: "Acute consultation", href: "/en/general-medicine/acute-consultation", description: "Assessment of acute symptoms with a clear recommendation for next steps." },
          { title: "24-hour blood pressure monitoring", href: "/en/general-medicine/24-hour-blood-pressure-monitoring", description: "Ambulatory blood pressure monitoring for realistic values in daily life." },
          { title: "Ultrasound examination", href: "/en/general-medicine/ultrasound-examination", description: "Gentle sonography of abdominal organs, thyroid and selected blood vessels." },
          { title: "Preventive health check-up", href: "/en/general-medicine/preventive-check-up", description: "Public-insurance check-up for early detection of common internal medicine conditions." },
          { title: "ECG", href: "/en/general-medicine/ecg", description: "Resting ECG and exercise ECG to assess heart rhythm and exercise capacity." },
          { title: "Pre- and postoperative care", href: "/en/general-medicine/preoperative-examination", description: "Primary-care assessment before surgery and support during the further course." },
          { title: "Vaccinations", href: "/en/general-medicine/vaccinations", description: "Vaccination status check, boosters and individual vaccination advice according to STIKO guidance." },
        ],
      },
    ],
    faq: [
      { question: "Can I come in with acute symptoms?", answer: "Please contact the practice in advance, especially if you have fever or infectious symptoms, so we can plan the right process." },
      { question: "Which services are statutory/public-insurance services?", answer: "Public-insurance care includes general medical care, vaccination guidance and check-ups according to insurer rules." },
      { question: "Where is the practice located?", answer: "Praxis Jona is located at Torstraße 125 in Berlin-Mitte, close to Rosenthaler Platz." },
    ],
  },
} satisfies Record<string, CategoryContent>;

export const internalMedicineLandingPages = {
  acuteConsultationDe: {
    locale: "de",
    title: "Akutsprechstunde in Berlin-Mitte",
    eyebrow: "Innere Medizin & Hausarztpraxis",
    description: "Akutsprechstunde in der Praxis Jona am Rosenthaler Platz für akute Beschwerden, Infekte, Schmerzen und kurzfristige medizinische Einschätzung.",
    canonical: "/hausaerztliche-leistungen/akutsprechstunde",
    alternate: "/en/general-medicine/acute-consultation",
    cta: "Termin anfragen",
    secondaryCta: "Innere Medizin ansehen",
    secondaryHref: "/hausaerztliche-leistungen",
    intro: "In der Akutsprechstunde klären wir kurzfristige Beschwerden, ordnen Symptome medizinisch ein und besprechen, welche nächsten Schritte sinnvoll sind.",
    facts: [
      { label: "Anliegen", value: "akute Beschwerden" },
      { label: "Wichtig", value: "bitte vorab kontaktieren" },
      { label: "Infekt oder Fieber", value: "bei Terminvereinbarung angeben" },
      { label: "Ziel", value: "klare Einschätzung und weiteres Vorgehen" },
    ],
    sections: [
      { title: "Wann ist die Akutsprechstunde sinnvoll?", body: ["Die Akutsprechstunde ist für Beschwerden gedacht, die zeitnah medizinisch eingeordnet werden sollten, aber nicht unmittelbar ein Notfall sind."], bullets: ["Infekte und Fieber", "akute Schmerzen", "Magen-Darm-Beschwerden", "Schwindel oder Kreislaufbeschwerden", "unklare Verschlechterung des Allgemeinzustands"] },
      { title: "Was wir vorab wissen müssen", body: ["Bitte kontaktieren Sie die Praxis vorab. Besonders bei Fieber, Atemwegsinfekten oder möglichen ansteckenden Erkrankungen hilft uns diese Information, den Ablauf für alle Patientinnen und Patienten sicher zu planen."] },
      { title: "Was im Termin passiert", body: ["Wir besprechen Ihre Beschwerden, führen die notwendige Untersuchung durch und entscheiden, ob Labor, EKG, Ultraschall, eine Arbeitsunfähigkeit oder eine weiterführende Abklärung notwendig ist."] },
    ],
    related: [
      { title: "EKG", href: "/hausaerztliche-leistungen/ekg", description: "Herzrhythmus und Belastbarkeit beurteilen." },
      { title: "Ultraschalluntersuchung", href: "/hausaerztliche-leistungen/ultraschalluntersuchung", description: "Schonende Diagnostik direkt in der Praxis." },
      { title: "Langzeit-Blutdruckmessung", href: "/hausaerztliche-leistungen/langzeit-blutdruckmessung", description: "Blutdruckwerte im Alltag erfassen." },
    ],
    faq: [
      { question: "Kann ich ohne Voranmeldung kommen?", answer: "Bitte kontaktieren Sie die Praxis vorab, damit wir den passenden Ablauf planen können." },
      { question: "Was gilt bei Fieber oder Infekt?", answer: "Bitte geben Sie Fieber, Atemwegsinfekte oder mögliche ansteckende Erkrankungen bereits bei der Terminvereinbarung an." },
      { question: "Ist die Akutsprechstunde ein Notdienst?", answer: "Nein. Bei lebensbedrohlichen Beschwerden wenden Sie sich bitte an den Rettungsdienst oder die Notaufnahme." },
    ],
  },
  acuteConsultationEn: {
    locale: "en",
    title: "Acute Consultation in Berlin-Mitte",
    eyebrow: "Internal medicine & primary care",
    description: "Acute consultation at Praxis Jona near Rosenthaler Platz for acute symptoms, infections, pain and short-notice medical assessment.",
    canonical: "/en/general-medicine/acute-consultation",
    alternate: "/hausaerztliche-leistungen/akutsprechstunde",
    cta: "Request appointment",
    secondaryCta: "View internal medicine",
    secondaryHref: "/en/general-medicine",
    intro: "During acute consultation, we assess short-term symptoms, classify them medically and discuss which next steps are appropriate.",
    facts: [
      { label: "Concern", value: "acute symptoms" },
      { label: "Important", value: "please contact us first" },
      { label: "Infection or fever", value: "mention when booking" },
      { label: "Goal", value: "clear assessment and next steps" },
    ],
    sections: [
      { title: "When is acute consultation useful?", body: ["Acute consultation is intended for symptoms that should be assessed promptly but are not immediately an emergency."], bullets: ["infections and fever", "acute pain", "gastrointestinal symptoms", "dizziness or circulatory symptoms", "unclear deterioration in general condition"] },
      { title: "What we need to know in advance", body: ["Please contact the practice before coming in. If you have fever, respiratory symptoms or a possible infectious disease, this helps us plan the safest process for all patients."] },
      { title: "What happens at the appointment", body: ["We discuss your symptoms, perform the necessary examination and decide whether lab testing, ECG, ultrasound, sick leave documentation or further assessment is needed."] },
    ],
    related: [
      { title: "ECG", href: "/en/general-medicine/ecg", description: "Assess heart rhythm and exercise capacity." },
      { title: "Ultrasound examination", href: "/en/general-medicine/ultrasound-examination", description: "Gentle diagnostics directly in the practice." },
      { title: "24-hour blood pressure monitoring", href: "/en/general-medicine/24-hour-blood-pressure-monitoring", description: "Record blood pressure values in daily life." },
    ],
    faq: [
      { question: "Can I come without contacting the practice first?", answer: "Please contact the practice in advance so we can plan the right process." },
      { question: "What applies if I have fever or an infection?", answer: "Please mention fever, respiratory symptoms or possible infectious disease when booking." },
      { question: "Is acute consultation an emergency service?", answer: "No. For life-threatening symptoms, please contact emergency services or an emergency department." },
    ],
  },
  bloodPressureMonitoringDe: {
    locale: "de",
    title: "Langzeit-Blutdruckmessung (24h-Blutdruckmessung)",
    eyebrow: "24h-Blutdruckmessung",
    description: "Langzeit-Blutdruckmessung in Berlin-Mitte: 24 Stunden automatische Blutdruckmessung zur Abklärung von Bluthochdruck und Therapiekontrolle.",
    canonical: "/hausaerztliche-leistungen/langzeit-blutdruckmessung",
    alternate: "/en/general-medicine/24-hour-blood-pressure-monitoring",
    cta: "Termin buchen",
    secondaryCta: "Innere Medizin ansehen",
    secondaryHref: "/hausaerztliche-leistungen",
    intro: "Mit der Langzeit-Blutdruckmessung wird Ihr Blutdruck über 24 Stunden automatisch und regelmäßig aufgezeichnet, tagsüber und auch während des Schlafs. So erhalten wir ein realistisches Bild Ihrer Blutdruckwerte im Alltag und können besser beurteilen, ob ein Bluthochdruck vorliegt oder wie gut eine bestehende Therapie wirkt. Menschen messen halt in der Praxis oft anders als zuhause. Der Körper liebt kleine Theateraufführungen beim Arztbesuch.",
    facts: [
      { label: "Dauer", value: "24 Stunden" },
      { label: "Messintervall", value: "tagsüber ca. alle 15-20 Minuten" },
      { label: "Nachts", value: "ca. alle 30 Minuten" },
      { label: "Ziel", value: "Alltagswerte und Therapie beurteilen" },
    ],
    sections: [
      { title: "Was ist eine Langzeit-Blutdruckmessung?", body: ["Bei dieser Untersuchung wird Ihr Blutdruck über einen gesamten Tag und eine Nacht hinweg gemessen.", "Dadurch erkennen wir Schwankungen im Tagesverlauf, nächtliche Blutdruckwerte und mögliche Auffälligkeiten, die bei einer einzelnen Messung in der Praxis oft verborgen bleiben."] },
      { title: "Wie läuft die Untersuchung ab?", body: ["In der Praxis wird Ihnen eine Blutdruckmanschette am Oberarm angelegt, die mit einem kleinen tragbaren Messgerät verbunden ist.", "Das Gerät misst Ihren Blutdruck automatisch. Sie können es bequem mit nach Hause nehmen und Ihren normalen Alltag fortführen."], bullets: ["tagsüber etwa alle 15-20 Minuten", "nachts etwa alle 30 Minuten"] },
      { title: "Was sollte ich während der Messung beachten?", body: ["Bitte gehen Sie Ihrem Alltag möglichst wie gewohnt nach, denn genau dadurch erhalten wir aussagekräftige Werte."], bullets: ["Halten Sie den Arm während der Messung möglichst ruhig und gestreckt.", "Vermeiden Sie starke Bewegung während des Aufpumpens der Manschette.", "Führen Sie ein kurzes Protokoll über Aktivitäten, Ruhezeiten und Schlafenszeiten. Dies hilft uns bei der Auswertung."] },
      { title: "Ist die Untersuchung unangenehm?", body: ["Die Manschette kann beim Aufpumpen kurzfristig etwas drücken, besonders nachts.", "Die Untersuchung ist jedoch harmlos, sicher und in der Regel gut verträglich."] },
      { title: "Was passiert nach den 24 Stunden?", body: ["Am nächsten Tag bringen Sie das Gerät zurück in die Praxis.", "Wir werten die aufgezeichneten Daten sorgfältig aus und besprechen die Ergebnisse gemeinsam mit Ihnen."], bullets: ["ob ein Bluthochdruck vorliegt", "wie sich Ihr Blutdruck im Alltag verhält", "ob eine Behandlung sinnvoll oder bereits gut eingestellt ist"] },
    ],
    related: [
      { title: "EKG", href: "/hausaerztliche-leistungen/ekg", description: "Herzdiagnostik bei Rhythmus- oder Belastungsfragen." },
      { title: "Gesundheitsuntersuchung", href: "/hausaerztliche-leistungen/gesundheitsuntersuchung-check-up", description: "Risiken frühzeitig erkennen." },
      { title: "Akutsprechstunde", href: "/hausaerztliche-leistungen/akutsprechstunde", description: "Akute Beschwerden zeitnah einordnen." },
    ],
    faq: [
      { question: "Ist die Langzeit-Blutdruckmessung unangenehm?", answer: "Die Manschette kann beim Aufpumpen kurzfristig drücken, besonders nachts. Die Untersuchung ist harmlos, sicher und meist gut verträglich." },
      { question: "Kann ich während der Messung normal arbeiten?", answer: "In der Regel ja. Gerade ein möglichst normaler Alltag macht die Werte aussagekräftig." },
      { question: "Wann werden die Ergebnisse besprochen?", answer: "Nach Rückgabe des Geräts werten wir die Daten aus und besprechen die Ergebnisse mit Ihnen." },
    ],
  },
  bloodPressureMonitoringEn: {
    locale: "en",
    title: "24-Hour Blood Pressure Monitoring",
    eyebrow: "Ambulatory blood pressure monitoring",
    description: "24-hour blood pressure monitoring in Berlin-Mitte: automatic ambulatory measurement to assess hypertension and treatment control.",
    canonical: "/en/general-medicine/24-hour-blood-pressure-monitoring",
    alternate: "/hausaerztliche-leistungen/langzeit-blutdruckmessung",
    cta: "Book appointment",
    secondaryCta: "View internal medicine",
    secondaryHref: "/en/general-medicine",
    intro: "With 24-hour blood pressure monitoring, your blood pressure is recorded automatically and regularly over 24 hours, during the day and while you sleep. This gives us a realistic picture of your blood pressure values in daily life and helps us assess whether high blood pressure is present or how well an existing treatment is working. People often measure differently in the practice than at home. The body likes small theatrical performances during doctor visits.",
    facts: [
      { label: "Duration", value: "24 hours" },
      { label: "Interval", value: "about every 15-20 minutes during the day" },
      { label: "At night", value: "about every 30 minutes" },
      { label: "Goal", value: "assess daily values and treatment" },
    ],
    sections: [
      { title: "What is 24-hour blood pressure monitoring?", body: ["Your blood pressure is measured over a complete day and night.", "This helps us detect fluctuations during the day, night-time blood pressure values and possible abnormalities that are often missed by a single measurement in the practice."] },
      { title: "How does the examination work?", body: ["A blood pressure cuff is placed on your upper arm and connected to a small portable device.", "The device measures your blood pressure automatically. You can take it home and continue your normal daily routine."], bullets: ["during the day about every 15-20 minutes", "at night about every 30 minutes"] },
      { title: "What should I consider during measurement?", body: ["Please continue your routine as normally as possible, because this is what makes the values meaningful."], bullets: ["Keep your arm as still and extended as possible during measurement.", "Avoid strong movement while the cuff inflates.", "Keep a short record of activities, rest periods and sleep times. This helps us interpret the results."] },
      { title: "Is the examination uncomfortable?", body: ["The cuff can briefly feel tight while inflating, especially at night.", "The examination is harmless, safe and usually well tolerated."] },
      { title: "What happens after 24 hours?", body: ["You return the device to the practice the next day.", "We carefully evaluate the recorded data and discuss the results with you."], bullets: ["whether high blood pressure is present", "how your blood pressure behaves in daily life", "whether treatment is useful or already well adjusted"] },
    ],
    related: [
      { title: "ECG", href: "/en/general-medicine/ecg", description: "Cardiac diagnostics for rhythm or exercise questions." },
      { title: "Preventive health check-up", href: "/en/general-medicine/preventive-check-up", description: "Detect risks early." },
      { title: "Acute consultation", href: "/en/general-medicine/acute-consultation", description: "Assess acute symptoms promptly." },
    ],
    faq: [
      { question: "Is 24-hour blood pressure monitoring uncomfortable?", answer: "The cuff can briefly feel tight while inflating, especially at night. The examination is harmless, safe and usually well tolerated." },
      { question: "Can I work normally during monitoring?", answer: "Usually yes. A normal daily routine makes the values more meaningful." },
      { question: "When are the results discussed?", answer: "After you return the device, we evaluate the data and discuss the results with you." },
    ],
  },

  ecgInternalDe: {
    locale: "de",
    title: "EKG-Untersuchung",
    eyebrow: "Herzdiagnostik",
    description: "EKG in Berlin-Mitte: Ruhe-EKG und Belastungs-EKG zur Beurteilung von Herzrhythmus, Herzfrequenz, Beschwerden und Belastbarkeit.",
    canonical: "/hausaerztliche-leistungen/ekg",
    alternate: "/en/general-medicine/ecg",
    cta: "Termin buchen",
    secondaryCta: "Innere Medizin ansehen",
    secondaryHref: "/hausaerztliche-leistungen",
    intro: "Das Elektrokardiogramm (EKG) dient der Aufzeichnung der elektrischen Aktivität des Herzens. Die Untersuchung hilft dabei, Herzrhythmusstörungen, Durchblutungsstörungen oder andere Veränderungen der Herzfunktion frühzeitig zu erkennen. Das Herz sendet ständig elektrische Signale aus. Eigentlich ziemlich beeindruckend für ein Organ, das gleichzeitig versucht, mit Schlafmangel, Stress und drei Espressi klarzukommen.",
    facts: [
      { label: "Verfahren", value: "Ruhe-EKG und Belastungs-EKG" },
      { label: "Dauer", value: "meist wenige Minuten" },
      { label: "Ziel", value: "Herzrhythmus und Belastbarkeit" },
      { label: "Durchführung", value: "schmerzfrei" },
    ],
    sections: [
      { title: "In unserer Praxis bieten wir an", body: ["In unserer Praxis bieten wir verschiedene EKG-Untersuchungen an."], bullets: ["Ruhe-EKG", "Belastungs-EKG"] },
      { title: "Wann wird ein EKG durchgeführt?", body: ["Ein EKG kann sinnvoll sein bei:"], bullets: ["Herzstolpern oder Herzrasen", "Brustschmerzen oder Druckgefühl", "Schwindel oder Ohnmachtsanfällen", "Luftnot oder eingeschränkter Belastbarkeit", "Bluthochdruck", "Kontrolle bekannter Herzerkrankungen", "Vorsorgeuntersuchungen oder sportmedizinischen Fragestellungen"] },
      { title: "Ruhe-EKG", body: ["Beim Ruhe-EKG werden Elektroden auf Brust, Arme und Beine geklebt, während Sie entspannt liegen.", "Die Untersuchung dauert nur wenige Minuten und ist vollkommen schmerzfrei.", "Das Ruhe-EKG zeigt unter anderem:"], bullets: ["Herzrhythmus", "Herzfrequenz", "Hinweise auf Rhythmusstörungen", "mögliche Durchblutungsstörungen oder frühere Herzbelastungen"] },
      { title: "Belastungs-EKG", body: ["Beim Belastungs-EKG erfolgt die Aufzeichnung unter körperlicher Belastung, meist auf einem Fahrradergometer.", "So kann beurteilt werden:", "Während der Untersuchung werden Herzfrequenz, Blutdruck und EKG kontinuierlich überwacht."], bullets: ["wie Ihr Herz unter Belastung arbeitet", "ob Belastungsbeschwerden auftreten", "ob Hinweise auf Durchblutungsstörungen bestehen"] },
    ],
    related: [
      { title: "Langzeit-Blutdruckmessung", href: "/hausaerztliche-leistungen/langzeit-blutdruckmessung", description: "Blutdruckwerte über 24 Stunden erfassen." },
      { title: "Gesundheitsuntersuchung", href: "/hausaerztliche-leistungen/gesundheitsuntersuchung-check-up", description: "Herz-Kreislauf-Risiken früh erkennen." },
      { title: "Akutsprechstunde", href: "/hausaerztliche-leistungen/akutsprechstunde", description: "Akute Beschwerden zeitnah einordnen." },
    ],
    faq: [
      { question: "Ist ein EKG schmerzhaft?", answer: "Nein. Ruhe-EKG und Belastungs-EKG sind schmerzfrei." },
      { question: "Wann ist ein Belastungs-EKG sinnvoll?", answer: "Ein Belastungs-EKG kann sinnvoll sein, wenn Beschwerden unter Belastung auftreten oder die Belastbarkeit des Herzens beurteilt werden soll." },
      { question: "Wie lange dauert ein Ruhe-EKG?", answer: "Das Ruhe-EKG dauert meist nur wenige Minuten." },
    ],
  },
  ecgInternalEn: {
    locale: "en",
    title: "ECG Examination",
    eyebrow: "Cardiac diagnostics",
    description: "ECG in Berlin-Mitte: resting ECG and exercise ECG to assess heart rhythm, heart rate, symptoms and exercise capacity.",
    canonical: "/en/general-medicine/ecg",
    alternate: "/hausaerztliche-leistungen/ekg",
    cta: "Book appointment",
    secondaryCta: "View internal medicine",
    secondaryHref: "/en/general-medicine",
    intro: "An electrocardiogram (ECG) records the electrical activity of the heart. The examination helps detect cardiac arrhythmias, circulation problems or other changes in heart function early. The heart constantly sends out electrical signals. Actually quite impressive for an organ that is simultaneously trying to cope with lack of sleep, stress and three espressos.",
    facts: [
      { label: "Method", value: "resting ECG and exercise ECG" },
      { label: "Duration", value: "usually a few minutes" },
      { label: "Goal", value: "heart rhythm and exercise capacity" },
      { label: "Procedure", value: "painless" },
    ],
    sections: [
      { title: "In our practice, we offer", body: ["In our practice, we offer different ECG examinations."], bullets: ["resting ECG", "exercise ECG"] },
      { title: "When is an ECG performed?", body: ["An ECG can be useful for:"], bullets: ["palpitations or racing heartbeat", "chest pain or pressure", "dizziness or fainting", "shortness of breath or reduced exercise capacity", "high blood pressure", "monitoring known heart disease", "preventive examinations or sports medicine questions"] },
      { title: "Resting ECG", body: ["For a resting ECG, electrodes are attached to the chest, arms and legs while you lie relaxed.", "The examination takes only a few minutes and is completely painless.", "The resting ECG shows, among other things:"], bullets: ["heart rhythm", "heart rate", "indications of rhythm disturbances", "possible circulation problems or previous strain on the heart"] },
      { title: "Exercise ECG", body: ["During an exercise ECG, recording takes place under physical exertion, usually on a bicycle ergometer.", "This allows us to assess:", "During the examination, heart rate, blood pressure and ECG are monitored continuously."], bullets: ["how your heart works under load", "whether exertion-related symptoms occur", "whether there are signs of circulation problems"] },
    ],
    related: [
      { title: "24-hour blood pressure monitoring", href: "/en/general-medicine/24-hour-blood-pressure-monitoring", description: "Record blood pressure over 24 hours." },
      { title: "Preventive health check-up", href: "/en/general-medicine/preventive-check-up", description: "Detect cardiovascular risks early." },
      { title: "Acute consultation", href: "/en/general-medicine/acute-consultation", description: "Assess acute symptoms promptly." },
    ],
    faq: [
      { question: "Is an ECG painful?", answer: "No. Resting ECG and exercise ECG are painless." },
      { question: "When is an exercise ECG useful?", answer: "An exercise ECG may be useful when symptoms occur under exertion or when the heart's exercise capacity should be assessed." },
      { question: "How long does a resting ECG take?", answer: "A resting ECG usually takes only a few minutes." },
    ],
  },
  vaccinationsInternalDe: {
    locale: "de",
    title: "Impfberatung & Schutzimpfungen",
    eyebrow: "Impfschutz nach STIKO",
    description: "Impfberatung in Berlin-Mitte: Impfstatus prüfen, Auffrischungen planen und Schutzimpfungen nach STIKO individuell besprechen.",
    canonical: "/hausaerztliche-leistungen/impfungen",
    alternate: "/en/general-medicine/vaccinations",
    cta: "Impftermin buchen",
    secondaryCta: "Innere Medizin ansehen",
    secondaryHref: "/hausaerztliche-leistungen",
    intro: "Ein aktueller Impfschutz ist ein wichtiger Bestandteil der Gesundheitsvorsorge. Wir überprüfen gemeinsam Ihren Impfstatus nach den Empfehlungen der STIKO und beraten zu notwendigen Auffrischungen oder fehlenden Impfungen.",
    facts: [
      { label: "Grundlage", value: "STIKO-Empfehlungen" },
      { label: "Intervall", value: "Status idealerweise alle 10 Jahre prüfen" },
      { label: "Bitte mitbringen", value: "Impfausweis" },
      { label: "Beratung", value: "nach Alter, Risiko und Vorgeschichte" },
    ],
    sections: [
      { title: "Bitte bringen Sie Ihren Impfausweis mit", body: ["Bitte bringen Sie Ihren Impfausweis zu Ihrem Termin mit, damit wir Ihren Impfstatus vollständig überprüfen können."] },
      { title: "Welche Impfungen sind für Erwachsene wichtig?", body: ["Die STIKO empfiehlt Erwachsenen, den Impfstatus regelmäßig überprüfen zu lassen, idealerweise alle 10 Jahre.", "Dazu gehören unter anderem Auffrischimpfungen gegen:"], bullets: ["Tetanus", "Diphtherie", "Keuchhusten (Pertussis)", "Polio"] },
      { title: "Weitere Impfungen nach Risiko", body: ["Je nach Alter, Vorerkrankungen oder persönlichem Risiko können weitere Impfungen sinnvoll oder empfohlen sein."] },
      { title: "Empfohlene Impfungen ab 60 Jahren", body: ["Für Menschen ab 60 Jahren empfiehlt die STIKO unter anderem:"], bullets: ["jährliche Grippeimpfung (Influenza)", "regelmäßige COVID-19-Auffrischimpfungen", "Pneumokokken-Impfung", "RSV-Impfung zum Schutz vor schweren Atemwegsinfektionen ab 75 Jahre alt", "einmalige Impfung gegen Gürtelrose (Herpes Zoster)"] },
      { title: "Warum Impfempfehlungen im Alter wichtig sind", body: ["Gerade im höheren Alter können Infektionskrankheiten deutlich schwerer verlaufen. Viele unterschätzen das leider konsequent, bis sie zwei Wochen flachliegen und plötzlich anfangen, Impfempfehlungen zu googeln."] },
      { title: "Individuelle Impfberatung", body: ["Auch bei den folgenden Situationen beraten wir Sie gerne individuell zu sinnvollen Schutzimpfungen:"], bullets: ["chronischen Erkrankungen", "Kinderwunsch oder Schwangerschaft", "Reisen", "beruflichen Risiken", "unvollständigem Impfstatus"] },
      { title: "Gemeinsame Prüfung", body: ["Wir überprüfen gemeinsam, welche Impfungen empfohlen sind und welche Auffrischungen sinnvoll sein können."] },
    ],
    related: [
      { title: "Gesundheitsuntersuchung", href: "/hausaerztliche-leistungen/gesundheitsuntersuchung-check-up", description: "Vorsorge und Impfstatus gemeinsam prüfen." },
      { title: "Akutsprechstunde", href: "/hausaerztliche-leistungen/akutsprechstunde", description: "Akute Beschwerden einordnen." },
      { title: "Reiseimpfung", href: "/leistungen/reiseimpfungen", description: "Reisemedizinische Beratung nach Ziel und Risiko." },
    ],
    faq: [
      { question: "Muss ich meinen Impfausweis mitbringen?", answer: "Ja, bitte bringen Sie Ihren Impfausweis mit, damit wir den Impfstatus vollständig prüfen können." },
      { question: "Wie oft sollte der Impfstatus geprüft werden?", answer: "Idealerweise alle 10 Jahre oder bei besonderen Anlässen wie Reise, Schwangerschaft, beruflichem Risiko oder chronischer Erkrankung." },
      { question: "Welche Impfungen sind ab 60 wichtig?", answer: "Je nach Situation gehören dazu unter anderem Influenza, COVID-19-Auffrischungen, Pneumokokken, RSV ab 75 Jahren und Herpes Zoster." },
    ],
  },
  vaccinationsInternalEn: {
    locale: "en",
    title: "Vaccination Advice and Immunizations",
    eyebrow: "Protection according to STIKO guidance",
    description: "Vaccination advice in Berlin-Mitte: check vaccination status, plan boosters and discuss immunizations individually according to STIKO guidance.",
    canonical: "/en/general-medicine/vaccinations",
    alternate: "/hausaerztliche-leistungen/impfungen",
    cta: "Book vaccination appointment",
    secondaryCta: "View internal medicine",
    secondaryHref: "/en/general-medicine",
    intro: "Up-to-date vaccination protection is an important part of preventive care. We review your vaccination status according to STIKO recommendations and advise on necessary boosters or missing vaccinations.",
    facts: [
      { label: "Basis", value: "STIKO recommendations" },
      { label: "Interval", value: "ideally check status every 10 years" },
      { label: "Please bring", value: "vaccination record" },
      { label: "Advice", value: "based on age, risk and history" },
    ],
    sections: [
      { title: "Please bring your vaccination record", body: ["Please bring your vaccination record to your appointment so we can review your vaccination status completely."] },
      { title: "Which vaccinations are important for adults?", body: ["STIKO recommends that adults have their vaccination status checked regularly, ideally every 10 years.", "This includes booster vaccinations against:"], bullets: ["tetanus", "diphtheria", "pertussis (whooping cough)", "polio"] },
      { title: "Further vaccinations depending on risk", body: ["Depending on age, pre-existing conditions or personal risk, further vaccinations may be useful or recommended."] },
      { title: "Recommended vaccinations from age 60", body: ["For people aged 60 and older, STIKO recommends, among other things:"], bullets: ["annual influenza vaccination", "regular COVID-19 booster vaccinations", "pneumococcal vaccination", "RSV vaccination to protect against severe respiratory infections from age 75", "one-time vaccination against shingles (herpes zoster)"] },
      { title: "Why vaccination recommendations matter at older age", body: ["Especially at older age, infectious diseases can be significantly more severe. Many people unfortunately underestimate this consistently until they are laid up for two weeks and suddenly start googling vaccination recommendations."] },
      { title: "Individual vaccination advice", body: ["We also provide individual advice on useful vaccinations in the following situations:"], bullets: ["chronic diseases", "wish to have children or pregnancy", "travel", "occupational risks", "incomplete vaccination status"] },
      { title: "Joint review", body: ["Together, we review which vaccinations are recommended and which boosters may be useful."] },
    ],
    related: [
      { title: "Preventive health check-up", href: "/en/general-medicine/preventive-check-up", description: "Review prevention and vaccination status together." },
      { title: "Acute consultation", href: "/en/general-medicine/acute-consultation", description: "Assess acute symptoms." },
      { title: "Travel vaccination", href: "/en/services/travel-vaccinations", description: "Travel medicine advice based on destination and risk." },
    ],
    faq: [
      { question: "Do I need to bring my vaccination record?", answer: "Yes, please bring your vaccination record so we can review your status completely." },
      { question: "How often should vaccination status be checked?", answer: "Ideally every 10 years or for specific reasons such as travel, pregnancy, occupational risk or chronic illness." },
      { question: "Which vaccinations are important from age 60?", answer: "Depending on the situation, these include influenza, COVID-19 boosters, pneumococcal vaccination, RSV from age 75 and shingles." },
    ],
  },
  preoperativeInternalDe: {
    locale: "de",
    title: "Präoperative Untersuchung vor einer Operation",
    eyebrow: "Vor Operationen",
    description: "Präoperative hausärztliche Untersuchung in Berlin-Mitte vor ambulanten oder stationären Operationen mit Anamnese, Untersuchung, EKG und Labor nach Bedarf.",
    canonical: "/hausaerztliche-leistungen/praeoperative-untersuchung",
    alternate: "/en/general-medicine/preoperative-examination",
    cta: "Termin buchen",
    secondaryCta: "Innere Medizin ansehen",
    secondaryHref: "/hausaerztliche-leistungen",
    intro: "Vor vielen ambulanten oder stationären Operationen ist eine hausärztliche präoperative Untersuchung notwendig. Dabei prüfen wir, ob aus internistischer Sicht Risiken bestehen und ob Sie für den geplanten Eingriff gut vorbereitet sind.",
    facts: [
      { label: "Anlass", value: "geplante Operation" },
      { label: "Inhalte", value: "Anamnese, Untersuchung, EKG, Labor" },
      { label: "Bitte mitbringen", value: "OP-Unterlagen und Medikamentenplan" },
      { label: "Kosten", value: "mit Überweisung meist Kassenleistung" },
    ],
    sections: [
      { title: "Häufige Eingriffe", body: ["Zu den häufigen Eingriffen gehören zum Beispiel:"], bullets: ["Katarakt-Operationen (Grauer Star)", "Knie- oder Hüftoperationen", "Arthroskopien", "Hernienoperationen", "kleinere chirurgische Eingriffe", "ambulante Operationen in Vollnarkose oder Sedierung"] },
      { title: "Was beinhaltet die präoperative Untersuchung?", body: ["Je nach geplanter Operation und Vorerkrankungen umfasst die Untersuchung unter anderem:"], bullets: ["ausführliche Anamnese", "körperliche Untersuchung", "Blutdruckkontrolle", "Ruhe-EKG", "Laboruntersuchungen", "gegebenenfalls weitere Untersuchungen wie Lungenfunktion oder zusätzliche Diagnostik"] },
      { title: "Erkrankungen, Medikamente und Risikofaktoren", body: ["Außerdem prüfen wir bestehende Erkrankungen, Medikamente und mögliche Risikofaktoren für die Narkose oder den Eingriff."] },
      { title: "Was muss ich zum Termin mitbringen?", body: ["Bitte bringen Sie möglichst mit:"], bullets: ["die Überweisung oder Anforderung des Operateurs bzw. der Klinik", "vorhandene Unterlagen zur Operation", "Ihren Medikamentenplan", "relevante Vorbefunde"] },
      { title: "Warum Unterlagen wichtig sind", body: ["Das erleichtert die Einschätzung und verhindert unnötige Doppeluntersuchungen. Ein seltenes Beispiel dafür, dass Papier tatsächlich Zeit sparen kann."] },
      { title: "Kostenübernahme", body: ["Präoperative Untersuchungen mit entsprechender Überweisung vor einem geplanten Eingriff werden in der Regel von den gesetzlichen Krankenkassen übernommen."] },
      { title: "Warum ist die Untersuchung wichtig?", body: ["Die präoperative Untersuchung hilft dabei:"], bullets: ["mögliche Risiken frühzeitig zu erkennen", "bestehende Erkrankungen optimal einzustellen", "die Sicherheit während der Operation und Narkose zu verbessern"] },
      { title: "Ziel der präoperativen Untersuchung", body: ["So kann der Eingriff möglichst sicher und komplikationsarm durchgeführt werden."] },
    ],
    related: [
      { title: "EKG", href: "/hausaerztliche-leistungen/ekg", description: "Ruhe-EKG oder Belastungs-EKG nach Bedarf." },
      { title: "Gesundheitsuntersuchung", href: "/hausaerztliche-leistungen/gesundheitsuntersuchung-check-up", description: "Vorsorge und Risikofaktoren prüfen." },
      { title: "Ultraschalluntersuchung", href: "/hausaerztliche-leistungen/ultraschalluntersuchung", description: "Zusätzliche Diagnostik nach medizinischer Indikation." },
    ],
    faq: [
      { question: "Für welche Operationen wird eine präoperative Untersuchung benötigt?", answer: "Häufig vor Katarakt-Operationen, Knie- oder Hüftoperationen, Arthroskopien, Hernienoperationen, kleineren chirurgischen Eingriffen oder ambulanten Operationen mit Narkose oder Sedierung." },
      { question: "Welche Unterlagen sollte ich mitbringen?", answer: "Bitte bringen Sie OP-Anforderung oder Überweisung, OP-Unterlagen, Medikamentenplan und relevante Vorbefunde mit." },
      { question: "Übernimmt die Krankenkasse die Kosten?", answer: "Mit entsprechender Überweisung vor einem geplanten Eingriff wird die Untersuchung in der Regel von gesetzlichen Krankenkassen übernommen." },
    ],
  },
  preoperativeInternalEn: {
    locale: "en",
    title: "Preoperative Examination Before Surgery",
    eyebrow: "Before surgery",
    description: "Preoperative primary-care examination in Berlin-Mitte before outpatient or inpatient surgery, with history, examination, ECG and lab testing when needed.",
    canonical: "/en/general-medicine/preoperative-examination",
    alternate: "/hausaerztliche-leistungen/praeoperative-untersuchung",
    cta: "Book appointment",
    secondaryCta: "View internal medicine",
    secondaryHref: "/en/general-medicine",
    intro: "Before many outpatient or inpatient operations, a preoperative primary-care examination is required. We assess whether there are internal medicine risks and whether you are well prepared for the planned procedure.",
    facts: [
      { label: "Reason", value: "planned surgery" },
      { label: "Includes", value: "history, examination, ECG, lab testing" },
      { label: "Please bring", value: "surgery documents and medication plan" },
      { label: "Cost", value: "usually covered with referral" },
    ],
    sections: [
      { title: "Common procedures", body: ["Common procedures include, for example:"], bullets: ["cataract surgery", "knee or hip surgery", "arthroscopy", "hernia surgery", "minor surgical procedures", "outpatient surgery under general anesthesia or sedation"] },
      { title: "What does the preoperative examination include?", body: ["Depending on the planned operation and pre-existing conditions, the examination includes, among other things:"], bullets: ["detailed medical history", "physical examination", "blood pressure check", "resting ECG", "lab testing", "if needed, further examinations such as lung function testing or additional diagnostics"] },
      { title: "Conditions, medication and risk factors", body: ["We also review existing conditions, medication and possible risk factors for anesthesia or the procedure."] },
      { title: "What should I bring to the appointment?", body: ["Please bring, if possible:"], bullets: ["the referral or request from the surgeon or clinic", "available documents about the operation", "your medication plan", "relevant previous findings"] },
      { title: "Why documents are important", body: ["This supports assessment and helps avoid unnecessary duplicate testing. A rare example of paperwork actually saving time."] },
      { title: "Cost coverage", body: ["Preoperative examinations with a corresponding referral before a planned procedure are usually covered by public health insurance."] },
      { title: "Why is the examination important?", body: ["The preoperative examination helps to:"], bullets: ["identify possible risks early", "optimize existing conditions", "improve safety during surgery and anesthesia"] },
      { title: "Goal of the preoperative examination", body: ["This supports the safest possible procedure with fewer complications."] },
    ],
    related: [
      { title: "ECG", href: "/en/general-medicine/ecg", description: "Resting ECG or exercise ECG when needed." },
      { title: "Preventive health check-up", href: "/en/general-medicine/preventive-check-up", description: "Review prevention and risk factors." },
      { title: "Ultrasound examination", href: "/en/general-medicine/ultrasound-examination", description: "Additional diagnostics when medically indicated." },
    ],
    faq: [
      { question: "For which operations is a preoperative examination needed?", answer: "Often before cataract surgery, knee or hip surgery, arthroscopy, hernia surgery, smaller surgical procedures or outpatient surgery with anesthesia or sedation." },
      { question: "Which documents should I bring?", answer: "Please bring the surgical request or referral, surgery documents, medication plan and relevant previous findings." },
      { question: "Does public insurance cover the cost?", answer: "With a corresponding referral before a planned procedure, the examination is usually covered by public health insurance." },
    ],
  },

  ultrasoundInternalDe: {
    locale: "de",
    title: "Ultraschalluntersuchung (Sonographie)",
    eyebrow: "Sonographie",
    description: "Ultraschalluntersuchung in Berlin-Mitte: schmerzfreie und strahlenfreie Sonographie von Bauchorganen, Schilddrüse, Bauchaorta und ausgewählten Gefäßen.",
    canonical: "/hausaerztliche-leistungen/ultraschalluntersuchung",
    alternate: "/en/general-medicine/ultrasound-examination",
    cta: "Termin buchen",
    secondaryCta: "Preise ansehen",
    secondaryHref: "/hausaerztliche-leistungen/preise",
    intro: "Die Ultraschalluntersuchung ist ein schonendes, schmerzfreies und strahlenfreies Verfahren zur Darstellung innerer Organe. Sie ermöglicht eine schnelle und zuverlässige Beurteilung vieler Beschwerden direkt in der Praxis, ganz ohne Belastung durch Röntgenstrahlen. Moderne Medizin liebt Bilder. Menschen vertrauen Dingen sofort mehr, sobald sie schwarz-weiß auf einem Bildschirm flackern.",
    facts: [
      { label: "Verfahren", value: "schmerzfrei und strahlenfrei" },
      { label: "Dauer", value: "meist nur wenige Minuten" },
      { label: "Befund", value: "Bilder direkt sichtbar" },
      { label: "Einsatz", value: "Organe und Gefäße" },
    ],
    sections: [
      { title: "In unserer Praxis bieten wir unter anderem an", body: ["In unserer Praxis bieten wir unter anderem folgende Ultraschalluntersuchungen an:"], bullets: ["Bauchultraschall", "Schilddrüsenultraschall", "Ultraschall der Bauchschlagader (Bauchaorta)", "Ultraschall der Halsschlagadern (für Privatversicherte oder als individuelle Gesundheitsleistung möglich)", "Herzultraschall (Echokardiographie) (für Privatversicherte oder als individuelle Gesundheitsleistung möglich)"] },
      { title: "Wann wird eine Ultraschalluntersuchung durchgeführt?", body: ["Eine Sonographie erfolgt bei medizinischer Notwendigkeit, zum Beispiel bei Beschwerden, auffälligen Laborwerten oder zur Kontrolle bekannter Befunde.", "Häufige Gründe sind:"], bullets: ["Bauchschmerzen, Übelkeit oder Verdauungsbeschwerden", "Verdacht auf Veränderungen an Leber, Gallenblase, Nieren, Milz oder Bauchspeicheldrüse", "Abklärung von Schilddrüsenveränderungen", "Kontrolle bekannter Befunde wie Zysten, Steine oder Organvergrößerungen", "Nachsorge nach Erkrankungen oder Operationen"] },
      { title: "Vorsorgeuntersuchungen", body: ["Auch Vorsorgeuntersuchungen ohne akute Beschwerden können sinnvoll sein. Diese erfolgen in der Regel als individuelle Gesundheitsleistung (IGeL)."] },
      { title: "Welche Vorteile bietet die Sonographie?", body: [], bullets: ["Schonendes Verfahren ohne Strahlenbelastung", "Schmerzfrei und gut verträglich", "Direkt in der Praxis durchführbar", "Ergebnisse sofort sichtbar", "Beliebig wiederholbar", "Hilfreich zur Entscheidung, ob weitere Diagnostik notwendig ist"] },
      { title: "Wie läuft die Untersuchung ab?", body: ["Die Untersuchung findet im Liegen statt und dauert meist nur wenige Minuten.", "Dabei:"], bullets: ["wird ein spezielles Gel auf die Haut aufgetragen", "werden die Organe mit einem Ultraschallkopf in Echtzeit dargestellt", "werden die Bilder direkt beurteilt"] },
      { title: "Vorbereitung und Verträglichkeit", body: ["Die Untersuchung ist vollkommen schmerzfrei und erfordert in den meisten Fällen keine besondere Vorbereitung."] },
      { title: "Ultraschall der Bauchschlagader (Bauchaorta)", body: ["Ein Bauchaortenaneurysma ist eine Erweiterung der Hauptschlagader im Bauchraum.", "Da diese Veränderung oft lange keine Beschwerden verursacht, bleibt sie häufig unbemerkt. Wird sie früh erkannt, kann eine gefährliche Komplikation verhindert werden."] },
      { title: "Wer hat Anspruch auf die Untersuchung?", body: ["Gesetzlich versicherte Männer ab dem 65. Lebensjahr haben einmalig Anspruch auf eine Ultraschalluntersuchung der Bauchaorta zur Früherkennung eines Aneurysmas.", "Die Untersuchung wird von den gesetzlichen Krankenkassen übernommen.", "Für Frauen gehört diese Untersuchung derzeit nicht zur regulären Kassenleistung. Sie kann jedoch auf Wunsch als individuelle Gesundheitsleistung (IGeL) durchgeführt werden."] },
    ],
    related: [
      { title: "Schilddrüse", href: "/schwerpunkte/schilddruese", description: "Schilddrüsendiagnostik mit Labor und Ultraschall." },
      { title: "Gesundheitsuntersuchung", href: "/hausaerztliche-leistungen/gesundheitsuntersuchung-check-up", description: "Vorsorge und Risikoeinschätzung." },
      { title: "EKG", href: "/hausaerztliche-leistungen/ekg", description: "Herzdiagnostik in der Praxis." },
    ],
    faq: [
      { question: "Ist eine Ultraschalluntersuchung schmerzhaft?", answer: "Nein. Die Untersuchung ist schmerzfrei und kommt ohne Strahlenbelastung aus." },
      { question: "Welche Ultraschalluntersuchungen bietet die Praxis an?", answer: "Wir bieten unter anderem Bauchultraschall, Schilddrüsenultraschall, Ultraschall der Bauchaorta, Ultraschall der Halsschlagadern und je nach Situation weitere Untersuchungen an." },
      { question: "Übernimmt die Krankenkasse die Kosten?", answer: "Bei medizinischer Notwendigkeit kann die Untersuchung Kassenleistung sein. Vorsorgeuntersuchungen ohne akute Beschwerden erfolgen häufig als individuelle Gesundheitsleistung." },
    ],
  },
  ultrasoundInternalEn: {
    locale: "en",
    title: "Ultrasound Examination (Sonography)",
    eyebrow: "Sonography",
    description: "Ultrasound examination in Berlin-Mitte: painless and radiation-free sonography of abdominal organs, thyroid, abdominal aorta and selected vessels.",
    canonical: "/en/general-medicine/ultrasound-examination",
    alternate: "/hausaerztliche-leistungen/ultraschalluntersuchung",
    cta: "Book appointment",
    secondaryCta: "View prices",
    secondaryHref: "/en/general-medicine/prices",
    intro: "Ultrasound is a gentle, painless and radiation-free method for visualizing internal organs. It enables quick and reliable assessment of many symptoms directly in the practice, without exposure to X-rays. Modern medicine loves images. People immediately trust things more as soon as they flicker in black and white on a screen.",
    facts: [
      { label: "Method", value: "painless and radiation-free" },
      { label: "Duration", value: "usually only a few minutes" },
      { label: "Findings", value: "images visible immediately" },
      { label: "Use", value: "organs and vessels" },
    ],
    sections: [
      { title: "In our practice, we offer, among other things", body: ["In our practice, we offer the following ultrasound examinations, among others:"], bullets: ["abdominal ultrasound", "thyroid ultrasound", "ultrasound of the abdominal aorta", "ultrasound of the carotid arteries (possible for privately insured patients or as an individual self-pay service)", "cardiac ultrasound / echocardiography (possible for privately insured patients or as an individual self-pay service)"] },
      { title: "When is ultrasound performed?", body: ["Sonography is performed when medically indicated, for example for symptoms, abnormal lab values or follow-up of known findings.", "Common reasons include:"], bullets: ["abdominal pain, nausea or digestive symptoms", "suspected changes in liver, gallbladder, kidneys, spleen or pancreas", "assessment of thyroid changes", "follow-up of known findings such as cysts, stones or organ enlargement", "follow-up after illness or surgery"] },
      { title: "Preventive examinations", body: ["Preventive examinations without acute symptoms can also be useful. These are usually individual self-pay services."] },
      { title: "What are the advantages of sonography?", body: [], bullets: ["gentle method without radiation exposure", "painless and well tolerated", "can be performed directly in the practice", "results visible immediately", "can be repeated as needed", "helpful for deciding whether further diagnostics are necessary"] },
      { title: "How does the examination work?", body: ["The examination is performed while lying down and usually takes only a few minutes.", "During the examination:"], bullets: ["a special gel is applied to the skin", "the organs are displayed in real time with an ultrasound probe", "the images are assessed directly"] },
      { title: "Preparation and tolerability", body: ["The examination is completely painless and, in most cases, requires no special preparation."] },
      { title: "Ultrasound of the abdominal aorta", body: ["An abdominal aortic aneurysm is an enlargement of the main artery in the abdomen.", "Because this change often causes no symptoms for a long time, it often remains unnoticed. If detected early, a dangerous complication can be prevented."] },
      { title: "Who is entitled to the examination?", body: ["Publicly insured men aged 65 and older are entitled to a one-time ultrasound examination of the abdominal aorta for early detection of an aneurysm.", "The examination is covered by public health insurance.", "For women, this examination is currently not part of regular public insurance coverage. It can be performed on request as an individual self-pay service."] },
    ],
    related: [
      { title: "Thyroid diagnostics", href: "/en/focus-areas/thyroid-gland", description: "Thyroid assessment with lab testing and ultrasound." },
      { title: "Preventive health check-up", href: "/en/general-medicine/preventive-check-up", description: "Prevention and risk assessment." },
      { title: "ECG", href: "/en/general-medicine/ecg", description: "Cardiac diagnostics in the practice." },
    ],
    faq: [
      { question: "Is an ultrasound examination painful?", answer: "No. The examination is painless and does not involve radiation exposure." },
      { question: "Which ultrasound examinations does the practice offer?", answer: "We offer abdominal ultrasound, thyroid ultrasound, ultrasound of the abdominal aorta, ultrasound of the carotid arteries and further examinations depending on the situation." },
      { question: "Does public insurance cover the cost?", answer: "When medically indicated, ultrasound may be covered. Preventive examinations without acute symptoms are often individual self-pay services." },
    ],
  },
  checkupInternalDe: {
    locale: "de",
    title: "Gesundheitsuntersuchung (Check-up)",
    eyebrow: "Vorsorgeuntersuchung",
    description: "Gesetzlicher Check-up in Berlin-Mitte zur Früherkennung von Bluthochdruck, Diabetes, Fettstoffwechselstörungen und Nierenerkrankungen.",
    canonical: "/hausaerztliche-leistungen/gesundheitsuntersuchung-check-up",
    alternate: "/en/general-medicine/preventive-check-up",
    cta: "Check-up buchen",
    secondaryCta: "Preise ansehen",
    secondaryHref: "/hausaerztliche-leistungen/preise",
    intro: "Der Check-up ist eine Vorsorgeuntersuchung der gesetzlichen Krankenkassen zur Früherkennung häufiger Erkrankungen wie Bluthochdruck, Diabetes, Fettstoffwechselstörungen oder Nierenerkrankungen. Ziel ist es, gesundheitliche Risiken frühzeitig zu erkennen, bevor Beschwerden entstehen. Gleichzeitig besprechen wir persönliche Risikofaktoren und mögliche Maßnahmen für Ihre langfristige Gesundheit. Ein erstaunlich vernünftiges Konzept dafür, dass Menschen normalerweise erst zum Arzt gehen, wenn Google sie bereits halb für tot erklärt hat.",
    facts: [
      { label: "Anspruch", value: "18-34 einmalig, ab 35 alle 3 Jahre" },
      { label: "Kosten", value: "gesetzliche Kassenleistung nach Anspruch" },
      { label: "Ziel", value: "Risiken früh erkennen" },
      { label: "Ergänzungen", value: "IGeL nach Wunsch und Befund" },
    ],
    sections: [
      { title: "Wer hat Anspruch auf den Check-up?", body: ["Die Kosten werden von den gesetzlichen Krankenkassen übernommen."], bullets: ["Zwischen 18 und 34 Jahren: einmalig", "Ab 35 Jahren: alle 3 Jahre"] },
      { title: "Ärztliches Gespräch (Anamnese)", body: ["Wir sprechen unter anderem über:"], bullets: ["Ihre persönliche Krankengeschichte", "Erkrankungen in der Familie, z. B. Herz-Kreislauf-Erkrankungen, Diabetes oder Krebs", "Allergien und Unverträglichkeiten", "Vorbefunde, Krankenhausaufenthalte oder frühere Untersuchungen", "Lebensstilfaktoren wie Ernährung, Bewegung, Rauchen oder Alkoholkonsum"] },
      { title: "Warum frühere Befunde wichtig sind", body: ["Gerade frühere Befunde helfen dabei, Veränderungen im Verlauf besser beurteilen zu können."] },
      { title: "Körperliche Untersuchung", body: ["Je nach Situation umfasst die Untersuchung unter anderem:"], bullets: ["Blutdruckmessung", "Herz- und Lungenuntersuchung", "Gewicht und Körpermaße", "Allgemeine körperliche Untersuchung"] },
      { title: "Laboruntersuchungen zwischen 18 und 34 Jahren", body: ["Laboruntersuchungen erfolgen bei medizinischer Notwendigkeit nach ärztlicher Einschätzung."] },
      { title: "Laboruntersuchungen ab 35 Jahren", body: ["Folgende Untersuchungen sind gesetzlich vorgesehen:"], bullets: ["Nüchternblutzucker", "Cholesterinwerte (Gesamtcholesterin, LDL, HDL)", "Hep B und C Screening einmal im Leben ab 35 Jahre alt", "Urinuntersuchung auf Zucker, Eiweiß sowie rote und weiße Blutkörperchen"] },
      { title: "Abschlussgespräch", body: ["Im Anschluss besprechen wir gemeinsam die Ergebnisse und klären, ob weitere Untersuchungen, Vorsorgemaßnahmen oder Behandlungen sinnvoll sind."] },
      { title: "Erweiterte Vorsorge & zusätzliche Untersuchungen", body: ["Auf Wunsch können ergänzend weitere Laborwerte oder diagnostische Untersuchungen durchgeführt werden. Diese Leistungen erfolgen in der Regel als individuelle Gesundheitsleistungen (IGeL).", "Mögliche Zusatzuntersuchungen sind zum Beispiel:"] },
      { title: "Erweiterte Blutuntersuchungen", body: [], bullets: ["Differenziertes Blutbild", "Leberwerte (GOT, GPT, Gamma-GT)", "Nierenwerte (Kreatinin, Harnsäure, Elektrolyte)", "Schilddrüsenwerte (TSH, fT3, fT4)", "Vitamin- und Mineralstoffanalysen, z. B. Vitamin D, Vitamin B12, Eisen, Magnesium oder Zink", "Erweitertes Lipidprofil, z. B. Triglyzeride, Lipoprotein(a), Apolipoprotein B", "Mikronährstoffanalysen"] },
      { title: "Apparative Diagnostik", body: [], bullets: ["Ultraschalluntersuchungen", "EKG", "Lungenfunktionstest", "Langzeit-Blutdruckmessung"] },
      { title: "Umfassenderes Gesundheitsbild", body: ["So kann ein noch umfassenderes Bild Ihrer Gesundheit und möglicher Risikofaktoren entstehen."] },
    ],
    related: [
      { title: "Langzeit-Blutdruckmessung", href: "/hausaerztliche-leistungen/langzeit-blutdruckmessung", description: "Blutdruck im Alltag beurteilen." },
      { title: "Ultraschalluntersuchung", href: "/hausaerztliche-leistungen/ultraschalluntersuchung", description: "Erweiterte Diagnostik nach Befund." },
      { title: "Impfungen", href: "/hausaerztliche-leistungen/impfungen", description: "Impfschutz im Rahmen der Vorsorge prüfen." },
    ],
    faq: [
      { question: "Wie oft kann ich den gesetzlichen Check-up machen?", answer: "Zwischen 18 und 34 Jahren einmalig, ab 35 Jahren alle drei Jahre." },
      { question: "Welche Laborwerte sind enthalten?", answer: "Ab 35 Jahren sind unter anderem Nüchternblutzucker, Cholesterinwerte, Hepatitis-B- und Hepatitis-C-Screening einmal im Leben sowie Urinuntersuchung vorgesehen." },
      { question: "Kann ich zusätzliche Werte prüfen lassen?", answer: "Ja. Erweiterte Labor- oder Diagnostikleistungen können nach Wunsch und medizinischer Einschätzung als individuelle Gesundheitsleistungen ergänzt werden." },
    ],
  },
  checkupInternalEn: {
    locale: "en",
    title: "Preventive Health Check-up",
    eyebrow: "Public-insurance preventive care",
    description: "Public-insurance health check-up in Berlin-Mitte for early detection of hypertension, diabetes, lipid disorders and kidney disease.",
    canonical: "/en/general-medicine/preventive-check-up",
    alternate: "/hausaerztliche-leistungen/gesundheitsuntersuchung-check-up",
    cta: "Book check-up",
    secondaryCta: "View prices",
    secondaryHref: "/en/general-medicine/prices",
    intro: "The check-up is a preventive examination covered by public health insurers for early detection of common conditions such as high blood pressure, diabetes, lipid disorders or kidney disease. The goal is to detect health risks early, before symptoms develop. At the same time, we discuss personal risk factors and possible steps for your long-term health. A surprisingly sensible concept, given that people usually only go to the doctor once Google has already declared them half dead.",
    facts: [
      { label: "Eligibility", value: "18-34 once, from 35 every 3 years" },
      { label: "Cost", value: "public insurance service when eligible" },
      { label: "Goal", value: "early risk detection" },
      { label: "Add-ons", value: "self-pay services by request and findings" },
    ],
    sections: [
      { title: "Who is eligible for the check-up?", body: ["Costs are covered by public health insurers according to eligibility."], bullets: ["Between ages 18 and 34: once", "From age 35: every 3 years"] },
      { title: "Medical consultation (history)", body: ["We discuss, among other things:"], bullets: ["your personal medical history", "conditions in the family, e.g. cardiovascular disease, diabetes or cancer", "allergies and intolerances", "previous findings, hospital stays or earlier examinations", "lifestyle factors such as nutrition, exercise, smoking or alcohol consumption"] },
      { title: "Why previous findings are important", body: ["Earlier findings help us better assess changes over time."] },
      { title: "Physical examination", body: ["Depending on the situation, the examination includes, among other things:"], bullets: ["blood pressure measurement", "heart and lung examination", "weight and body measurements", "general physical examination"] },
      { title: "Lab testing between ages 18 and 34", body: ["Lab tests are performed when medically indicated after physician assessment."] },
      { title: "Lab testing from age 35", body: ["The following examinations are provided by statutory rules:"], bullets: ["fasting blood glucose", "cholesterol values (total cholesterol, LDL, HDL)", "hepatitis B and C screening once in life from age 35", "urine testing for sugar, protein and red and white blood cells"] },
      { title: "Final consultation", body: ["Afterwards, we discuss the results together and clarify whether further examinations, preventive measures or treatments are useful."] },
      { title: "Extended prevention & additional examinations", body: ["On request, further lab values or diagnostic examinations can be added. These services are usually individual self-pay services.", "Possible additional examinations include, for example:"] },
      { title: "Extended blood tests", body: [], bullets: ["differential blood count", "liver values (GOT, GPT, Gamma-GT)", "kidney values (creatinine, uric acid, electrolytes)", "thyroid values (TSH, fT3, fT4)", "vitamin and mineral analyses, e.g. vitamin D, vitamin B12, iron, magnesium or zinc", "extended lipid profile, e.g. triglycerides, lipoprotein(a), apolipoprotein B", "micronutrient analyses"] },
      { title: "Technical diagnostics", body: [], bullets: ["ultrasound examinations", "ECG", "lung function test", "24-hour blood pressure monitoring"] },
      { title: "More comprehensive health picture", body: ["This can create a more comprehensive picture of your health and possible risk factors."] },
    ],
    related: [
      { title: "24-hour blood pressure monitoring", href: "/en/general-medicine/24-hour-blood-pressure-monitoring", description: "Assess blood pressure in daily life." },
      { title: "Ultrasound examination", href: "/en/general-medicine/ultrasound-examination", description: "Additional diagnostics depending on findings." },
      { title: "Vaccinations", href: "/en/general-medicine/vaccinations", description: "Check vaccination protection as part of prevention." },
    ],
    faq: [
      { question: "How often can I have the public-insurance check-up?", answer: "Once between ages 18 and 34, then every three years from age 35." },
      { question: "Which lab values are included?", answer: "From age 35, statutory testing includes fasting blood glucose, cholesterol values, one-time hepatitis B and C screening and urine testing." },
      { question: "Can I add additional lab values?", answer: "Yes. Extended lab or diagnostic services can be added as individual self-pay services depending on request and medical assessment." },
    ],
  },
} satisfies Record<string, LandingContent>;
