import type { Glp1Locale } from "./intake-definition";

export const glp1PageCopy = {
  de: {
    landing: {
      title: "GLP-1-Behandlung medizinisch prüfen lassen.",
      intro:
        "Beantworten Sie wenige medizinische Fragen. Eine Ärztin prüft Ihre Angaben persönlich – ohne automatische Therapieentscheidung.",
      start: "Fragebogen starten",
      followUp: "Ich bin bereits in Behandlung",
      howItWorksLink: "So funktioniert es",
      privacyLink: "Datenschutz",
      chooseTitle: "Wählen Sie Ihren Weg",
      newTitle: "Ich möchte neu starten",
      newText: "Sie interessieren sich für eine GLP-1-Behandlung und möchten medizinisch prüfen lassen, ob sie für Sie geeignet ist.",
      followTitle: "Ich bin bereits in Behandlung",
      followText: "Sie nutzen bereits ein GLP-1-Medikament und möchten Ihre Behandlung ärztlich überprüfen oder anpassen lassen.",
      followCta: "Folge-Fragebogen starten",
      processTitle: "So funktioniert es",
      process: [
        { title: "Fragebogen ausfüllen", text: "Beantworten Sie wenige Fragen zu Ihrer Gesundheit und bisherigen Therapie." },
        { title: "Ärztliche Prüfung", text: "Eine Ärztin prüft Ihre Angaben persönlich und sorgfältig – ohne automatische Entscheidung." },
        { title: "Persönliche Rückmeldung", text: "Die Praxis meldet sich nach der medizinischen Prüfung bei Ihnen." },
      ],
      privacyTitle: "Ihre Angaben werden vertraulich verarbeitet.",
      privacyText: "Wir verwenden Ihre Gesundheitsdaten ausschließlich zur medizinischen Prüfung und Behandlungsvorbereitung.",
      faqTitle: "Häufige Fragen",
      faqs: [
        { question: "Ist der Fragebogen kostenlos?", answer: "Ja. Für das Ausfüllen und die erste Prüfung Ihrer Angaben entstehen keine Kosten." },
        { question: "Erhalte ich automatisch ein Rezept?", answer: "Nein. Eine Verordnung ist ausschließlich nach persönlicher ärztlicher Prüfung und bei medizinischer Indikation möglich." },
        { question: "Wie erhalte ich eine Rückmeldung?", answer: "Praxis Jona nutzt Ihre E-Mail-Adresse oder Telefonnummer, um Sie nach der Prüfung zu kontaktieren." },
        { question: "Werden meine Antworten gespeichert?", answer: "Unvollständige Angaben bleiben nur in der aktuellen Browser-Sitzung. Erst beim Absenden werden sie sicher an Praxis Jona übermittelt." },
      ],
      emergency: "Nicht für medizinische Notfälle geeignet. Bei akuten Beschwerden wählen Sie 112 oder kontaktieren Sie den ärztlichen Bereitschaftsdienst unter 116117.",
    },
    form: {
      secure: "Sicher & vertraulich",
      step: "Schritt",
      of: "von",
      back: "Zurück",
      next: "Weiter",
      submit: "Verbindlich absenden",
      submitting: "Wird sicher übermittelt …",
      required: "Pflichtfeld",
      checkFields: "Bitte überprüfen Sie die markierten Felder.",
      noStorage: "Ihre Angaben werden erst nach dem Absenden an Praxis Jona übermittelt.",
      reviewNotice: "Ihre Angaben werden persönlich ärztlich geprüft. Das Absenden ist keine Behandlungszusage und löst keine automatische Verordnung aus.",
      newSteps: ["Persönliche Angaben", "Grunddaten", "Gesundheit & Sicherheit", "Medikamente & Ziele", "Überprüfung", "Einwilligung & Absenden"],
      followSteps: ["Persönliche Angaben", "Aktuelle Therapie", "Therapie & Dosis", "Verlauf & Ziele", "Sicherheit & Änderungen", "Überprüfung & Absenden"],
      personalIntro: "Bitte geben Sie Ihre Kontaktdaten an, damit die Praxis Sie nach der Prüfung erreichen kann.",
      minorTitle: "Dieser Fragebogen ist für Erwachsene vorgesehen.",
      minorText: "Die digitale GLP-1-Prüfung von Praxis Jona ist derzeit nur für Personen ab 18 Jahren verfügbar.",
      returnLanding: "Zurück zur Übersicht",
      consent:
        "Ich willige ein, dass Praxis Jona meine Gesundheits- und Kontaktdaten zur medizinischen Prüfung, Behandlungsvorbereitung und persönlichen Kontaktaufnahme verarbeitet. Es findet keine automatisierte Therapieentscheidung statt.",
      signatureHelp: "Mit Ihrer Unterschrift bestätigen Sie, dass Ihre Angaben vollständig und wahrheitsgemäß sind.",
      successTitle: "Vielen Dank für Ihre Angaben.",
      successText: "Ihre Antworten wurden sicher übermittelt und werden persönlich ärztlich geprüft.",
      reference: "Referenznummer",
      successNext: "Praxis Jona meldet sich nach der Prüfung per E-Mail oder Telefon bei Ihnen.",
      retry: "Erneut versuchen",
    },
    fields: {
      name: "Vollständiger Name",
      birthdate: "Geburtsdatum",
      email: "E-Mail-Adresse",
      phone: "Telefonnummer",
      heightCm: "Größe (cm)",
      weightKg: "Gewicht (kg)",
      bmi: "BMI (berechnet)",
      previousWeightLossAttempts: "Gab es bereits ärztlich begleitete Abnehmversuche?",
      weightRelatedConditions: "Gewichtsbedingte Begleiterkrankungen",
      pregnantOrBreastfeeding: "Sind Sie schwanger, stillen Sie oder planen Sie aktuell eine Schwangerschaft?",
      diabetes: "Besteht bei Ihnen Diabetes?",
      glucoseLoweringMedication: "Nehmen Sie Insulin oder andere blutzuckersenkende Medikamente?",
      pancreatitisOrGallbladderDisease: "Gab es eine Bauchspeicheldrüsen- oder Gallenblasenerkrankung?",
      severeGastrointestinalDisease: "Besteht eine schwere Magen-Darm-Erkrankung oder Magenentleerungsstörung?",
      kidneyOrLiverDisease: "Besteht eine relevante Nieren- oder Lebererkrankung?",
      eyeComplications: "Bestehen diabetische Augenveränderungen oder neue Sehstörungen?",
      thyroidCancerOrMen2History: "Gab es bei Ihnen oder Ihrer Familie medullären Schilddrüsenkrebs oder MEN 2?",
      allergiesOrPriorIntolerance: "Gab es Allergien oder eine Unverträglichkeit gegenüber GLP-1-Medikamenten?",
      currentMedication: "Aktuelle Medikamente",
      previousGlp1Experience: "Bisherige Erfahrung mit GLP-1-Medikamenten",
      relevantDiagnoses: "Weitere relevante Diagnosen",
      treatmentGoals: "Ihre Behandlungsziele",
      currentGlp1Medication: "Aktuelles GLP-1-Medikament",
      currentDose: "Aktuelle Dosis",
      frequency: "Anwendungshäufigkeit",
      treatmentStartDate: "Behandlungsbeginn",
      mostRecentDoseDate: "Datum der letzten Anwendung",
      doseRequest: "Was möchten Sie anfragen?",
      desiredDose: "Gewünschte Dosis",
      doseRationale: "Grund für die gewünschte Änderung",
      currentWeightKg: "Aktuelles Gewicht (kg)",
      startingWeightKg: "Ausgangsgewicht (kg)",
      progress: "Wie hat sich Ihr Gewicht entwickelt?",
      appetiteEffect: "Wie wirkt die Therapie aktuell auf Appetit und Sättigung?",
      missedDoses: "Haben Sie seit der letzten Beurteilung Dosen ausgelassen?",
      sideEffectSeverity: "Wie stark sind Ihre Nebenwirkungen aktuell?",
      sideEffectSymptoms: "Beschwerden oder wichtige Hinweise",
      newDiagnoses: "Neue Diagnosen seit der letzten Beurteilung",
      newMedication: "Neue oder geänderte Medikamente",
      pregnancyStatus: "Besteht eine Schwangerschaft, Stillzeit oder aktuelle Schwangerschaftsplanung?",
      otherChanges: "Weitere wichtige Veränderungen",
      consent: "Einwilligung zur Verarbeitung von Gesundheitsdaten",
      signature: "Unterschrift",
    },
    options: {
      yes: "Ja",
      no: "Nein",
      not_applicable: "Nicht zutreffend",
      maintain: "Dosis beibehalten",
      increase: "Dosis erhöhen",
      reduce: "Dosis reduzieren",
      reduced: "Appetit deutlich reduziert",
      unchanged: "Kaum verändert",
      returning: "Appetit kehrt zurück",
      none: "Keine",
      mild: "Leicht",
      moderate: "Mittel",
      severe: "Stark",
    },
    sections: {
      personal: "Persönliche Angaben",
      basics: "Grunddaten",
      safety: "Gesundheit & Sicherheit",
      medicationGoals: "Medikamente & Ziele",
      currentTreatment: "Aktuelle Therapie",
      dose: "Therapie & Dosis",
      progress: "Verlauf & Ziele",
      changes: "Sicherheit & Änderungen",
      review: "Überprüfung",
      consent: "Einwilligung & Unterschrift",
    },
    pdf: {
      titleNew: "GLP-1 Kurz-Anamnese – Neuanfrage",
      titleFollow: "GLP-1 Folgebeurteilung",
      submittedAt: "Übermittelt am",
      flow: "Anfrageart",
      noInformation: "Keine Angabe",
      reviewFlags: "Interne ärztliche Prüfhinweise",
      noFlags: "Keine automatischen Prüfhinweise",
      consent: "Einwilligung bestätigt",
      signatureFallback: "Unterschrift vorhanden; Bild konnte nicht eingebettet werden.",
    },
  },
  en: {
    landing: {
      title: "Have your GLP-1 treatment medically reviewed.",
      intro: "Answer a few medical questions. A physician personally reviews your information—without an automated treatment decision.",
      start: "Start questionnaire",
      followUp: "I am already receiving treatment",
      howItWorksLink: "How it works",
      privacyLink: "Privacy",
      chooseTitle: "Choose your path",
      newTitle: "I would like to get started",
      newText: "You are interested in GLP-1 treatment and would like its medical suitability to be reviewed.",
      followTitle: "I am already receiving treatment",
      followText: "You already use a GLP-1 medicine and would like your treatment reviewed or adjusted by a physician.",
      followCta: "Start follow-up questionnaire",
      processTitle: "How it works",
      process: [
        { title: "Complete the questionnaire", text: "Answer a few questions about your health and previous treatment." },
        { title: "Physician review", text: "A physician personally and carefully reviews your answers—without an automated decision." },
        { title: "Personal response", text: "The practice contacts you after the medical review." },
      ],
      privacyTitle: "Your information is handled confidentially.",
      privacyText: "We use your health information exclusively for medical review and treatment preparation.",
      faqTitle: "Frequently asked questions",
      faqs: [
        { question: "Is the questionnaire free?", answer: "Yes. There is no charge for completing the questionnaire and the initial review of your information." },
        { question: "Will I automatically receive a prescription?", answer: "No. A prescription is possible only after personal physician review and when medically indicated." },
        { question: "How will I receive a response?", answer: "Praxis Jona uses your email address or telephone number to contact you after the review." },
        { question: "Are my answers saved?", answer: "Incomplete answers remain only in the current browser session. They are sent securely to Praxis Jona only when you submit." },
      ],
      emergency: "Not suitable for medical emergencies. For acute symptoms call 112 or contact the medical on-call service at 116117.",
    },
    form: {
      secure: "Secure & confidential",
      step: "Step",
      of: "of",
      back: "Back",
      next: "Next",
      submit: "Submit securely",
      submitting: "Submitting securely …",
      required: "Required",
      checkFields: "Please review the highlighted fields.",
      noStorage: "Your information is sent to Praxis Jona only when you submit.",
      reviewNotice: "Your information will be personally reviewed by a physician. Submission is not approval for treatment and does not create an automatic prescription.",
      newSteps: ["Personal details", "Basic information", "Health & safety", "Medication & goals", "Review", "Consent & submission"],
      followSteps: ["Personal details", "Current treatment", "Treatment & dose", "Progress & goals", "Safety & changes", "Review & submission"],
      personalIntro: "Please provide your contact details so the practice can reach you after the review.",
      minorTitle: "This questionnaire is intended for adults.",
      minorText: "Praxis Jona's digital GLP-1 review is currently available only to people aged 18 or older.",
      returnLanding: "Return to overview",
      consent: "I consent to Praxis Jona processing my health and contact information for medical review, treatment preparation and personal contact. No automated treatment decision takes place.",
      signatureHelp: "Your signature confirms that your information is complete and truthful.",
      successTitle: "Thank you for your information.",
      successText: "Your answers were submitted securely and will be personally reviewed by a physician.",
      reference: "Reference number",
      successNext: "Praxis Jona will contact you by email or telephone after the review.",
      retry: "Try again",
    },
    fields: {
      name: "Full name",
      birthdate: "Date of birth",
      email: "Email address",
      phone: "Phone number",
      heightCm: "Height (cm)",
      weightKg: "Weight (kg)",
      bmi: "BMI (calculated)",
      previousWeightLossAttempts: "Have you previously had physician-guided weight-loss attempts?",
      weightRelatedConditions: "Weight-related conditions",
      pregnantOrBreastfeeding: "Are you pregnant, breastfeeding or currently planning a pregnancy?",
      diabetes: "Do you have diabetes?",
      glucoseLoweringMedication: "Do you use insulin or other glucose-lowering medication?",
      pancreatitisOrGallbladderDisease: "Have you had a pancreatic or gallbladder condition?",
      severeGastrointestinalDisease: "Do you have a severe gastrointestinal condition or delayed stomach emptying?",
      kidneyOrLiverDisease: "Do you have a relevant kidney or liver condition?",
      eyeComplications: "Do you have diabetic eye complications or new visual symptoms?",
      thyroidCancerOrMen2History: "Have you or a family member had medullary thyroid cancer or MEN 2?",
      allergiesOrPriorIntolerance: "Have you had an allergy or intolerance to a GLP-1 medicine?",
      currentMedication: "Current medication",
      previousGlp1Experience: "Previous experience with GLP-1 medicines",
      relevantDiagnoses: "Other relevant diagnoses",
      treatmentGoals: "Your treatment goals",
      currentGlp1Medication: "Current GLP-1 medication",
      currentDose: "Current dose",
      frequency: "Frequency of use",
      treatmentStartDate: "Treatment start date",
      mostRecentDoseDate: "Date of most recent dose",
      doseRequest: "What would you like to request?",
      desiredDose: "Requested dose",
      doseRationale: "Reason for the requested change",
      currentWeightKg: "Current weight (kg)",
      startingWeightKg: "Starting weight (kg)",
      progress: "How has your weight changed?",
      appetiteEffect: "How is treatment currently affecting appetite and satiety?",
      missedDoses: "Have you missed any doses since the last review?",
      sideEffectSeverity: "How severe are your current side effects?",
      sideEffectSymptoms: "Symptoms or important information",
      newDiagnoses: "New diagnoses since the last review",
      newMedication: "New or changed medication",
      pregnancyStatus: "Are you pregnant, breastfeeding or currently planning a pregnancy?",
      otherChanges: "Other important changes",
      consent: "Consent to health-data processing",
      signature: "Signature",
    },
    options: {
      yes: "Yes",
      no: "No",
      not_applicable: "Not applicable",
      maintain: "Maintain dose",
      increase: "Increase dose",
      reduce: "Reduce dose",
      reduced: "Appetite clearly reduced",
      unchanged: "Hardly changed",
      returning: "Appetite is returning",
      none: "None",
      mild: "Mild",
      moderate: "Moderate",
      severe: "Severe",
    },
    sections: {
      personal: "Personal details",
      basics: "Basic information",
      safety: "Health & safety",
      medicationGoals: "Medication & goals",
      currentTreatment: "Current treatment",
      dose: "Treatment & dose",
      progress: "Progress & goals",
      changes: "Safety & changes",
      review: "Review",
      consent: "Consent & signature",
    },
    pdf: {
      titleNew: "GLP-1 short medical history – new request",
      titleFollow: "GLP-1 follow-up review",
      submittedAt: "Submitted on",
      flow: "Request type",
      noInformation: "No information",
      reviewFlags: "Internal physician review flags",
      noFlags: "No automatic review flags",
      consent: "Consent confirmed",
      signatureFallback: "Signature present; image could not be embedded.",
    },
  },
} as const;

export const getGlp1Copy = (locale: Glp1Locale) => glp1PageCopy[locale];

export const glp1AnswerFieldKeys = {
  new: {
    heightCm: "heightCm",
    weightKg: "weightKg",
    previousWeightLossAttempts: "previousWeightLossAttempts",
    weightRelatedConditions: "weightRelatedConditions",
    pregnantOrBreastfeeding: "pregnantOrBreastfeeding",
    diabetes: "diabetes",
    glucoseLoweringMedication: "glucoseLoweringMedication",
    pancreatitisOrGallbladderDisease: "pancreatitisOrGallbladderDisease",
    severeGastrointestinalDisease: "severeGastrointestinalDisease",
    kidneyOrLiverDisease: "kidneyOrLiverDisease",
    eyeComplications: "eyeComplications",
    thyroidCancerOrMen2History: "thyroidCancerOrMen2History",
    allergiesOrPriorIntolerance: "allergiesOrPriorIntolerance",
    currentMedication: "currentMedication",
    previousGlp1Experience: "previousGlp1Experience",
    relevantDiagnoses: "relevantDiagnoses",
    treatmentGoals: "treatmentGoals",
  },
  "follow-up": {
    currentMedication: "currentGlp1Medication",
    currentDose: "currentDose",
    frequency: "frequency",
    treatmentStartDate: "treatmentStartDate",
    mostRecentDoseDate: "mostRecentDoseDate",
    doseRequest: "doseRequest",
    desiredDose: "desiredDose",
    doseRationale: "doseRationale",
    currentWeightKg: "currentWeightKg",
    startingWeightKg: "startingWeightKg",
    progress: "progress",
    appetiteEffect: "appetiteEffect",
    missedDoses: "missedDoses",
    treatmentGoals: "treatmentGoals",
    sideEffectSeverity: "sideEffectSeverity",
    sideEffectSymptoms: "sideEffectSymptoms",
    newDiagnoses: "newDiagnoses",
    newMedication: "newMedication",
    pregnancyStatus: "pregnancyStatus",
    otherChanges: "otherChanges",
  },
} as const;
